#!/bin/sh

GITLAB_PROJECT_ID=53243565
CI_LINT_OUTPUT=/tmp/gitlab-ci-lint.json

status=0

if [ -n "${GITLAB_ACCESS_TOKEN}" ]; then
  CONTENT="$(cat .gitlab-ci.yml)"
  jq --null-input --arg yaml "$CONTENT" '.content=$yaml' | \
  curl -s "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/ci/lint" \
    --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
    --data @- > $CI_LINT_OUTPUT
  if [ "$(jq -r .valid <"$CI_LINT_OUTPUT")" != "true" ]; then
    status=1
    echo "errors: $(jq .errors < "$CI_LINT_OUTPUT")"
    echo "warnings: $(jq .warnings < "$CI_LINT_OUTPUT")"
  fi
else
  echo "please export GITLAB_ACCESS_TOKEN"
  exit 1
fi
echo "status after gitlab lint: $status"

xvfb-run sbt test || status=1
echo "status after sbt test: $status"

xvfb-run sbt "run --level 3 --timeout 0.1" || status=1
echo "status after sbt run: $status"

sbt "Universal / packageBin" || status=1
VERSION=$(grep 'version :=' build.sbt | cut -d '"' -f 2)
unzip -oq ./target/universal/menger-${VERSION}.zip || status=1
xvfb-run ./menger-${VERSION}/bin/menger --level 2 --timeout 0.1 --lines || status=1
echo "status after running built: $status"

#docker build --build-arg version="$VERSION" -t test_image . || status=1
#echo "status after docker build: $status"

if [ $status -gt 0 ]; then
  commit_msg=$(git log --oneline | head -n 1 | cut -d' ' -f 2-)
  if echo "$commit_msg" | grep '^WIP:'; then
    echo >&2 "Found WIP commit, pushing in spite of failed test suite"
    status=0
  fi
fi

exit $status
