package menger.engines.scene

import com.badlogic.gdx.math.Vector3
import menger.ObjectSpec
import menger.ProfilingConfig
import menger.Projection4DSpec
import menger.common.TriangleMeshData
import menger.objects.Cube
import menger.objects.SpongeBySurface
import menger.objects.SpongeByVolume
import menger.objects.higher_d.TesseractMesh

/**
 * Factory for creating triangle meshes from ObjectSpec.
 *
 * Centralizes mesh generation logic for all supported geometry types:
 * - cube: Simple cube mesh
 * - sponge-volume: Menger sponge generated by volume removal
 * - sponge-surface: Menger sponge generated by surface subdivision
 * - tesseract: 4D hypercube projected to 3D
 *
 * All meshes are created centered at origin (0, 0, 0) with the specified size.
 * Positioning is handled separately via instance transforms.
 */
object MeshFactory:

  /**
   * Create a triangle mesh for the given ObjectSpec.
   *
   * @param spec Object specification with geometry type and parameters
   * @param profilingConfig Profiling configuration (required for sponge-surface)
   * @return Triangle mesh data ready for OptiX
   * @throws IllegalArgumentException if objectType is unknown or required parameters are missing
   */
  def create(spec: ObjectSpec)(using profilingConfig: ProfilingConfig): TriangleMeshData =
    spec.objectType match
      case "cube" =>
        val cube = Cube(center = Vector3(0f, 0f, 0f), scale = spec.size)
        cube.toTriangleMesh

      case "sponge-volume" =>
        require(spec.level.isDefined, "sponge-volume requires level parameter")
        val sponge = SpongeByVolume(
          center = Vector3(0f, 0f, 0f),
          scale = spec.size,
          level = spec.level.get
        )
        sponge.toTriangleMesh

      case "sponge-surface" =>
        require(spec.level.isDefined, "sponge-surface requires level parameter")
        val sponge = SpongeBySurface(
          center = Vector3(0f, 0f, 0f),
          scale = spec.size,
          level = spec.level.get
        )
        sponge.toTriangleMesh

      case "tesseract" =>
        val proj = spec.projection4D.getOrElse(Projection4DSpec.default)
        val tesseract = TesseractMesh(
          center = Vector3(0f, 0f, 0f),
          size = spec.size,
          eyeW = proj.eyeW,
          screenW = proj.screenW,
          rotXW = proj.rotXW,
          rotYW = proj.rotYW,
          rotZW = proj.rotZW
        )
        tesseract.toTriangleMesh

      case other =>
        require(false, s"Unknown mesh type: $other")
        ???  // Never reached due to require, but needed for type checker
