package menger.engines.scene

import com.badlogic.gdx.math.Vector3
import menger.ObjectSpec
import menger.Projection4DSpec
import menger.common.ObjectType
import menger.common.ProfilingConfig
import menger.common.TriangleMeshData
import menger.objects.Cube
import menger.objects.Dodecahedron
import menger.objects.Icosahedron
import menger.objects.Octahedron
import menger.objects.SpongeBySurface
import menger.objects.SpongeByVolume
import menger.objects.Tetrahedron
import menger.objects.higher_d.Hecatonicosachoron
import menger.objects.higher_d.Hexacosichoron
import menger.objects.higher_d.Hexadecachoron
import menger.objects.higher_d.Icositetrachoron
import menger.objects.higher_d.Mesh4DGpuFlatten
import menger.objects.higher_d.Mesh4DProjection
import menger.objects.higher_d.Pentachoron
import menger.objects.higher_d.TesseractMesh
import menger.objects.higher_d.TesseractSponge2Mesh
import menger.objects.higher_d.TesseractSpongeMesh

/**
 * Factory for creating triangle meshes from ObjectSpec.
 *
 * Centralizes mesh generation logic for all supported geometry types:
 * - cube: Simple cube mesh
 * - sponge-volume: Menger sponge generated by volume removal
 * - sponge-surface: Menger sponge generated by surface subdivision
 * - tesseract: 4D hypercube projected to 3D
 * - tesseract-sponge: 4D Menger sponge (volume-based) projected to 3D
 * - tesseract-sponge-2: 4D Menger sponge (surface-based) projected to 3D
 * - tetrahedron: Regular tetrahedron (4 triangular faces)
 * - octahedron: Regular octahedron (8 triangular faces)
 * - icosahedron: Regular icosahedron (20 triangular faces)
 * - dodecahedron: Regular dodecahedron (12 pentagonal faces, triangulated)
 *
 * All meshes are created centered at origin (0, 0, 0) with the specified size.
 * Positioning is handled separately via instance transforms.
 */
object MeshFactory:

  /**
   * Create a triangle mesh for the given ObjectSpec.
   *
   * @param spec Object specification with geometry type and parameters
   * @param profilingConfig Profiling configuration (required for sponge-surface)
   * @return Triangle mesh data ready for OptiX
   * @throws IllegalArgumentException if objectType is unknown or required parameters are missing
   */
  def create(spec: ObjectSpec)(using profilingConfig: ProfilingConfig): TriangleMeshData =
    spec.objectType match
      case "cube" =>
        val cube = Cube(center = Vector3(0f, 0f, 0f), scale = spec.size)
        cube.toTriangleMesh

      case "sponge-volume" =>
        require(spec.level.isDefined, "sponge-volume requires level parameter")
        val sponge = SpongeByVolume(
          center = Vector3(0f, 0f, 0f),
          scale = spec.size,
          level = spec.level.get
        )
        sponge.toTriangleMesh

      case "sponge-recursive-ias" =>
        // The leaf of a recursive-IAS sponge is always a unit cube; the sponge
        // shape comes from N nested IAS layers wrapping that cube via the 20
        // Menger generator transforms (see addRecursiveIASSpongeInstance).
        // spec.size is applied via the outer instance transform, not the mesh.
        Cube(center = Vector3(0f, 0f, 0f), scale = 1f).toTriangleMesh

      case "sponge-surface" =>
        require(spec.level.isDefined, "sponge-surface requires level parameter")
        val sponge = SpongeBySurface(
          center = Vector3(0f, 0f, 0f),
          scale = spec.size,
          level = spec.level.get
        )
        sponge.toTriangleMesh

      case "tesseract" =>
        mesh4DProjection(spec).get.toTriangleMesh

      case "tesseract-sponge" | "tesseract-sponge-volume" =>
        require(spec.level.isDefined, "tesseract-sponge requires level parameter")
        mesh4DProjection(spec).get.toTriangleMesh

      case "tesseract-sponge-2" | "tesseract-sponge-surface" =>
        require(spec.level.isDefined, "tesseract-sponge-2 requires level parameter")
        mesh4DProjection(spec).get.toTriangleMesh

      case "pentachoron" | "16-cell" | "24-cell" | "120-cell" | "600-cell" =>
        mesh4DProjection(spec).get.toTriangleMesh

      case "tetrahedron" =>
        Tetrahedron(center = Vector3(0f, 0f, 0f), scale = spec.size).toTriangleMesh

      case "octahedron" =>
        Octahedron(center = Vector3(0f, 0f, 0f), scale = spec.size).toTriangleMesh

      case "icosahedron" =>
        Icosahedron(center = Vector3(0f, 0f, 0f), scale = spec.size).toTriangleMesh

      case "dodecahedron" =>
        Dodecahedron(center = Vector3(0f, 0f, 0f), scale = spec.size).toTriangleMesh

      case "parametric" =>
        @SuppressWarnings(Array("org.wartremover.warts.Throw"))
        def getMesh = spec.meshData.getOrElse(
          throw new IllegalStateException("Parametric surface missing pre-tessellated mesh data")
        )
        getMesh

      case other =>
        sys.error(s"Unknown mesh type: $other")

  /** Build a `MeshUploadPlan` for the given spec. 4D-projected types always use
    * the GPU path: a `Gpu4D` plan carrying the flat 4D-quad buffer + projection
    * params, projected on the GPU. All other (3D) types use the CPU `create(spec)`
    * triangle mesh.
    *
    * `skinOffset` is reserved for expanding the lower-level mesh of a fractional
    * pair along face normals (`FractionalLevelSponge.SkinNormalOffset`). */
  def createUpload(
    spec: ObjectSpec,
    skinOffset: Float = 0f
  )(using profilingConfig: ProfilingConfig): MeshUploadPlan =
    if ObjectType.isProjected4D(spec.objectType) then
      gpu4DPlan(spec, skinOffset).getOrElse(
        sys.error(s"No GPU 4D projection available for type: ${spec.objectType}")
      )
    else
      MeshUploadPlan.Cpu(create(spec))

  private def gpu4DPlan(spec: ObjectSpec, skinOffset: Float = 0f): Option[MeshUploadPlan.Gpu4D] =
    mesh4DProjection(spec).map { p =>
      // A non-zero skinOffset expands the lower-level mesh of a fractional pair
      // outward along its 4D face normals before projection, so its surface does
      // not land coincident with the higher-level surface and z-fight. This is the
      // GPU equivalent of the CPU path's TriangleMeshData.expandAlongNormals; only
      // quad meshes (the 4D sponges that take a skin offset) support it.
      val (buffer, vpf) =
        if skinOffset != 0f then
          (Mesh4DGpuFlatten.quadsBuffer(p.mesh4D, skinOffset), p.mesh4D.vertsPerFace)
        else
          Mesh4DGpuFlatten.facesBuffer(p.mesh4D)
      MeshUploadPlan.Gpu4D(
        quads4D = buffer,
        vertsPerFace = vpf,
        proj = spec.projection4D.getOrElse(Projection4DSpec.default)
      )
    }

  private def mesh4DProjection(spec: ObjectSpec): Option[Mesh4DProjection] =
    val proj = spec.projection4D.getOrElse(Projection4DSpec.default)
    spec.objectType match
      case "tesseract" =>
        Some(TesseractMesh(
          center = Vector3(0f, 0f, 0f), size = spec.size,
          eyeW = proj.eyeW, screenW = proj.screenW,
          rotXW = proj.rotXW, rotYW = proj.rotYW, rotZW = proj.rotZW
        ))
      case "tesseract-sponge" | "tesseract-sponge-volume" if spec.level.isDefined =>
        Some(TesseractSpongeMesh(
          center = Vector3(0f, 0f, 0f), size = spec.size,
          level = spec.level.get,
          eyeW = proj.eyeW, screenW = proj.screenW,
          rotXW = proj.rotXW, rotYW = proj.rotYW, rotZW = proj.rotZW
        ))
      case "tesseract-sponge-2" | "tesseract-sponge-surface" if spec.level.isDefined =>
        Some(TesseractSponge2Mesh(
          center = Vector3(0f, 0f, 0f), size = spec.size,
          level = spec.level.get,
          eyeW = proj.eyeW, screenW = proj.screenW,
          rotXW = proj.rotXW, rotYW = proj.rotYW, rotZW = proj.rotZW
        ))
      case "pentachoron" =>
        Some(Mesh4DProjection(
          mesh4D = Pentachoron(size = spec.size),
          eyeW = proj.eyeW, screenW = proj.screenW,
          rotXW = proj.rotXW, rotYW = proj.rotYW, rotZW = proj.rotZW
        ))
      case "16-cell" =>
        Some(Mesh4DProjection(
          mesh4D = Hexadecachoron(size = spec.size),
          eyeW = proj.eyeW, screenW = proj.screenW,
          rotXW = proj.rotXW, rotYW = proj.rotYW, rotZW = proj.rotZW
        ))
      case "24-cell" =>
        Some(Mesh4DProjection(
          mesh4D = Icositetrachoron(size = spec.size),
          eyeW = proj.eyeW, screenW = proj.screenW,
          rotXW = proj.rotXW, rotYW = proj.rotYW, rotZW = proj.rotZW
        ))
      case "600-cell" =>
        Some(Mesh4DProjection(
          mesh4D = Hexacosichoron(size = spec.size),
          eyeW = proj.eyeW, screenW = proj.screenW,
          rotXW = proj.rotXW, rotYW = proj.rotYW, rotZW = proj.rotZW
        ))
      case "120-cell" =>
        Some(Mesh4DProjection(
          mesh4D = Hecatonicosachoron(size = spec.size),
          eyeW = proj.eyeW, screenW = proj.screenW,
          rotXW = proj.rotXW, rotYW = proj.rotYW, rotZW = proj.rotZW
        ))
      case _ => None
