package menger.objects

import scala.math.abs

import com.badlogic.gdx.graphics.g3d.utils.MeshPartBuilder.VertexInfo
import menger.common.Vec3
import menger.objects.Direction.X
import menger.objects.Direction.Y
import menger.objects.Direction.Z


// Menger Sponge Face Subdivision Algorithm
//
// A Menger sponge surface is generated by recursive subdivision of each face.
// At each level, a face subdivides into 12 sub-faces:
//   - 8 "unrotated" sub-faces: in the same plane, forming a ring around the center
//   - 4 "rotated" sub-faces: perpendicular to the original, forming the inner walls
//
// The unrotated faces form a 3x3 grid minus the center (8 faces).
// The rotated faces are positioned at the 4 cardinal edges of the center hole,
// each rotated 90 degrees to face inward, creating the tunnel walls.
//
// This creates the characteristic Menger sponge pattern where:
//   - Each face has a square hole in the center
//   - The hole connects to perpendicular tunnels
//   - The pattern repeats at each subdivision level

case class Face(xCen: Float, yCen: Float, zCen: Float, scale: Float, normal: Direction)
    extends TriangleMeshSource:

  private type QuadInfo = (VertexInfo, VertexInfo, VertexInfo, VertexInfo)

  def subdivide(): Seq[Face] =
    unrotatedSubFaces ++ rotatedSubFaces

  lazy val vertices: QuadInfo =
    val half = scale / 2
    normal match
      case X | Direction.negX => createVertices((0, -half, -half), (0, -half, half), (0, half, half), (0, half, -half))
      case Y | Direction.negY => createVertices((-half, 0, -half), (half, 0, -half), (half, 0, half), (-half, 0, half))
      case Z | Direction.negZ => createVertices((-half, -half, 0), (half, -half, 0), (half, half, 0), (-half, half, 0))

  private def createVertices(offsets: Vec3[Float]*): QuadInfo =
    offsets.map { case (dx, dy, dz) => VertexInfo().setPos(xCen + dx, yCen + dy, zCen + dz) } match
      case Seq(v1, v2, v3, v4) => (v1, v2, v3, v4)

  def toTriangleMesh: TriangleMeshData =
    val half = scale / 2
    val n = normal.toFloatArray
    // Face vertices are in the plane perpendicular to normal, at distance 0 from center
    // The center (xCen, yCen, zCen) should already be positioned correctly by the caller
    val offsets: Seq[Vec3[Float]] = normal match
      case X | Direction.negX => Seq((0f, -half, -half), (0f, -half, half), (0f, half, half), (0f, half, -half))
      case Y | Direction.negY => Seq((-half, 0f, -half), (half, 0f, -half), (half, 0f, half), (-half, 0f, half))
      case Z | Direction.negZ => Seq((-half, -half, 0f), (half, -half, 0f), (half, half, 0f), (-half, half, 0f))

    // UV coordinates for quad corners: (0,0), (1,0), (1,1), (0,1)
    val uvs = Seq((0f, 0f), (1f, 0f), (1f, 1f), (0f, 1f))

    val verts = offsets.zip(uvs).flatMap { case ((dx, dy, dz), (u, v)) =>
      Seq(xCen + dx, yCen + dy, zCen + dz, n(0), n(1), n(2), u, v)
    }.toArray

    val indices = Array(0, 1, 2, 0, 2, 3)
    TriangleMeshData(verts, indices, 8)

  // 8 sub-faces in the same plane: 3x3 grid minus center
  // Condition abs(x) + abs(y) > 0 excludes only (0,0), keeping the 8 surrounding positions
  private lazy val unrotatedSubFaces: Seq[Face] =
    for (x <- -1 to 1; y <- -1 to 1 if abs(x) + abs(y) > 0)
      yield Face(runningCoordinates(x/3f, y/3f, scale), scale / 3f, normal)

  // 4 sub-faces perpendicular to the original, forming tunnel walls
  // Each is positioned at a cardinal direction from center, rotated 90 degrees around that axis
  // fold1/fold2 are the two axes perpendicular to this face's normal
  private lazy val rotatedSubFaces: Seq[Face] =
    for(
      (x, y, axis) <- Seq(
        (0f, -1/3f, normal.fold1), (1/3f, 0f, normal.fold2),
        (0f, 1/3f, -normal.fold1), (-1/3f, 0f, -normal.fold2)
      )
    ) yield Face(
      runningCoordinatesShifted(x, y, scale, -scale/3f), scale / 3f, normal.rotate90(axis)
    )

  private def runningCoordinates(x1: Float, x2: Float, add: Float): Vec3[Float] =
    normal match
      case X | Direction.negX => (xCen, yCen + x1 * add, zCen + x2 * add)
      case Y | Direction.negY => (xCen + x2 * add, yCen, zCen + x1 * add)
      case Z | Direction.negZ => (xCen + x1 * add, yCen + x2 * add, zCen)

  private def runningCoordinatesShifted(
    x1: Float, x2: Float, add: Float, shift: Float
  ): Vec3[Float] =
    normal match
      case X | Direction.negX => (xCen + shift / 2 * normal.sign, yCen + x1 * add / 2, zCen + x2 * add / 2)
      case Y | Direction.negY => (xCen + x2 * add / 2, yCen + shift / 2 * normal.sign, zCen + x1 * add / 2)
      case Z | Direction.negZ => (xCen + x1 * add / 2, yCen + x2 * add / 2, zCen + shift / 2 * normal.sign)

object Face:
  def apply(xyzCen: Vec3[Float], scale: Float, normal: Direction): Face =
    Face(xyzCen.x, xyzCen.y, xyzCen.z, scale, normal)
